### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by iMrShadow** [deng0/DirectXTexNet#11]
Hello! 
The app that I am developing uses Avalonia UI. However, DirectXTexNet does not support Linux.
Can Linux support be added? If not, what are the work-arounds? I tried using Wine, but Avalonia does not like it (window appears, but content is black. I tried configuring Wine, but no success so far).

**Comment by deng0** [comment]
The way this wrapper is set up (mixed mode assembly), it's highly unlikely that this wrapper will ever work for linux.

As discussed in the other issue, it might be good to take a look at the other wrapper:
https://www.nuget.org/packages/HexaEngine.DirectXTex
