### ISSUE TITLE
DirectXTexNet not available in Unity?

### ISSUE THREAD

**Issue by F1mmel** [deng0/DirectXTexNet#12]
Hey,

I hope you can help me. I am trying to do some image processing in my game in unity. When importing both dll files (the lib and the native), unity can't import them. I assume this is because this wrapper uses  C++/CLR, right?

Is it somehow possible I can still use it?
If you need aditional information, let me know!

Thanks in advance!
Finn

**Comment by deng0** [comment]
I would suggest you take a look at the newer alternative:
https://github.com/HexaEngine/Hexa.NET.DirectXTex

**Comment by F1mmel** [comment]
Thanks, worked!
