### ISSUE TITLE
I see NetStandard... when can I expect NuGet?

### ISSUE THREAD

**Issue by malware-dev** [deng0/DirectXTexNet#4]
I'm writing a library where I need your excellent wrapper - but I'd prefer keeping it a NetStandard library, which currently doesn't work.

I go here to ask if this is something that might happen, and what do I see? "changed to netstandard2.0"... last month. How excellent is _that?_ 😄 

so... now, instead, I humbly ask when I might see a NuGet package update with this change...?

Thank you in advance!

**Comment by deng0** [comment]
No problem, I have uploaded the nuget package now. Should be listed any minute now.

The library that will be referenced by your project is now a NET Standard 2.0 library, but the library that contains the actual DirectXTex implementation is C++/CLI and, as I understand it, will only be supported by .NET Core 3 on windows, which I have successfully tested with .NET Core 3 (Preview 7).

Let me know, whether rc4 works for you.
