### ISSUE TITLE
Wrapper for DirectXMesh

### ISSUE THREAD

**Issue by cz-dev-ge** [deng0/DirectXTexNet#5]
Hi there,
great work : )

Any chance that you could make a wrapper of [DirectXMesh](https://github.com/microsoft/DirectXMesh)?

Cheers,
Georg

**Comment by deng0** [comment]
Hi Georg,

nice to hear that you like it.

Regarding DirectXMesh: No, I don't think I will create a wrapper for it.
Although not really in the same category, but you might have a look at [AssimpNet](https://bitbucket.org/Starnick/assimpnet/src/master/).

**Comment by cz-dev-ge** [comment]
I'll have a look. Thank you. : )
